### PR TITLE
Use hyper-native-tls for fetching data

### LINKED ISSUE #15: Incompatible with systems using openssl 1.1
... like Debian.

I'm not sure what's up with the openssl mess in Rust. Can you poke the dependencies somehow, maybe?

### PR DESCRIPTION
**Pull request by whitequark**
This PR fixes #15. Also probably improves Windows compatibility.

### CODE REVIEW

**Comment by whitequark** [comment]
Updated to fix rink-web. rink-irc is broken due to https://github.com/aatxe/irc/issues/62.

**Comment by polyzen** [comment]
Any chance for a new release? :)

**Comment by whitequark** [comment]
@polyzen If you're interested in fixing aatxe/irc I can tell you how to do it.

**Comment by polyzen** [comment]
Thank you for the offer, but I don't use rink-irc.

**Pull request merged**
